---

- name: Set other manager role
  set_fact:
    other_manager_role: "{% if manager_role=='m' %}s{% else %}m{%endif %}"

- name: Set other manager role
  set_fact:
    other_manager_hostname: "{% for host in groups['leofs_manager'] %}{% if other_manager_role == hostvars[host].manager_role %}{{ host }}{% endif %}{% endfor %}"

- name: Set other manager role
  set_fact:
    instance: "{% if manager_role=='m' %}0{% else %}1{%endif %}"
    other_instance: "{% if manager_role=='m' %}1{% else %}0{%endif %}"

- name: Define nodename in conf file
  lineinfile:
    dest: /usr/local/leofs/leofs_current/leo_manager_{{ instance }}/etc/leo_manager.conf
    regexp: '^nodename'
    line: 'nodename = manager_{{ instance }}@{{ inventory_hostname }}'

- name: Define manager.partner in conf file
  lineinfile:
    dest: /usr/local/leofs/leofs_current/leo_manager_{{ instance }}/etc/leo_manager.conf
    regexp: '^manager.partner'
    line: 'manager.partner = manager_{{ other_instance }}@{{ other_manager_hostname }}'

- name: Define Consistency Level
  lineinfile:
    dest: /usr/local/leofs/leofs_current/leo_manager_0/etc/leo_manager.conf
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} = {{ item.val }}'
  with_items:
    - { key: consistency.num_of_replicas, val: 3 }
    - { key: consistency.write, val: 2 }
    - { key: consistency.read, val: 1 }
    - { key: consistency.delete, val: 2 }
    - { key: consistency.rack_aware_replicas, val: 0 }
  when: manager_role=='m'

- name: Start Master Manager
  shell: /usr/local/leofs/leofs_current/leo_manager_{{ instance }}/bin/leo_manager start
  when: manager_role=='m'

- name: Start Slave Manager
  shell: /usr/local/leofs/leofs_current/leo_manager_{{ instance }}/bin/leo_manager start
  when: manager_role=='s'
