---

- name: Installation de Flask (server web pour l'API REST)
  yum: 
    name: python-flask
    state: present

- name: Installation .py ditrit pour les managers
  copy: 
    src: "{{ item }}"
    dest: /usr/local/bin/
  with_items:
    - "../../../manager/"
    - "../../../utils/"


