---

- name: Installation de Flask (server web pour l'API REST)
  yum: 
    name: python-flask
    state: present

- name: Installation modules python via pip
  pip: 
    name: flask-restplus

- name: Installation .py ditrit pour les managers
  copy: 
    src: "{{ item }}"
    dest: /usr/local/bin/
  with_items:
    - "../../../ditrit/manager.py"
    - "../../../ditrit/manager"
    - "../../../ditrit/utils"
    - "../../../ditrit/tosca"
    - "../../../ditrit/example"

- name: Déploiement du service ditritmanager
  copy:
    src: 'ditritmanager.service'
    dest: /etc/systemd/system/ditritmanager.service
    owner: root
    mode: 750

- name: Demarrage du service
  systemd:
    name: ditritmanager
    enabled: yes
    state: started

