---

- name: Define nodename in conf file
  lineinfile:
    dest: /usr/local/leofs/leofs_current/leo_gateway/etc/leo_gateway.conf
    regexp: '^managers'
    line: "managers = [{% for host in groups['leofs_manager'] %}{% if hostvars[host].manager_role=='m' %}manager_0@{{ host }}{% endif %}{% if hostvars[host].manager_role=='s' %}manager_1@{{ host }}{% endif %}{% if not loop.last %},{% endif %}{% endfor %}]"

- name: Define nodename in conf file
  lineinfile:
    dest: /usr/local/leofs/leofs_current/leo_gateway/etc/leo_gateway.conf
    regexp: '^nodename'
    line: 'nodename = gateway_{{ instance }}@{{ inventory_hostname }}'

- name: Start Gateway
  shell: /usr/local/leofs/leofs_current/leo_gateway/bin/leo_gateway start

- name: Register as service in consul
  uri:
    url: http://localhost:8500/v1/agent/service/register
    method: PUT
    body: '{"Name": "s3", "Port": 8080 }'
    body_format: json
