---

- name: Installation .py ditrit pour les workers operations
  copy: 
    src: "{{ item }}"
    dest: /usr/local/bin/
  with_items:
    - "../../../workers/oet.py"
    - "../../../workers/cache_csar.py"
    - "../../../utils/linda.py"

- name: Installation config watches consul pour les workers operations
  copy: 
    src: "{{ item }}"
    dest: /etc/consul.d/
  with_items:
    - "../../../workers/oet.json"

