---

- name: Installation .py ditrit pour les workers operations
  copy: 
    src: "{{ item }}"
    dest: /usr/local/bin/
  with_items:
    - "../../../ditrit/exec_operation.py"
    - "../../../ditrit/cache_csar.py"
    - "../../../ditrit/utils"

- name: Installation config watches consul pour les workers operations
  copy: 
    src: "{{ item }}"
    dest: /etc/consul.d/
  with_items:
    - "../../../ditrit/consul_watches/watch_operation.json"

