---

- name: Configuration du consul agent
  template: 
    src: consul_agent.json.j2
    dest: /etc/consul.d/consul_agent.json

- name: Demarrage du service
  systemd:
    name: consul
    enabled: yes
    state: started

