---

- name: Installation epel
  yum: 
    name: epel-release
    state: present

- name: Installation des prerequis ditrit 
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-six
    - PyYAML
    - python-requests
    - python-flask 
    - python-pip
    - python-boto

- name: Fichier logs
  file:
    path: /opt/execs
    state: touch

