---
- name: Déploiement du binaire consul
  unarchive:
    src: '{{ consul_zip }}'
    dest: /var/lib/lxc/{{ item.name }}/rootfs/usr/local/bin/
  with_items: 
   - "{{ containers }}"

- name: Repertoire de configuration consul
  file:
    path: /var/lib/lxc/{{ item.name }}/rootfs/etc/consul.d
    state: directory
  with_items:
    - "{{ containers }}"

- name: Déploiement du binaire consul
  copy:
    src: 'consul.service'
    dest: /var/lib/lxc/{{ item.name }}/rootfs/etc/systemd/system/consul.service
  with_items: 
   - "{{ containers }}"

- name: Déploiement configuration consul server
  template: 
    src: consul_server.json.j2
    dest: /var/lib/lxc/{{ item.name }}/rootfs/etc/consul.d/consul_server.json
  with_items:
    - "{{ containers }}"

- name: Repertoire consul-data
  file:
    path: /var/lib/lxc/{{ item.name }}/rootfs/var/consul
    state: directory
  with_items:
    - "{{ containers }}"

- name: Generation du node-id necessaire en conteneur
  shell: cat /proc/sys/kernel/random/uuid > /var/lib/lxc/{{ item.name }}/rootfs/var/consul/node-id
  with_items:
    - "{{ containers }}"

- name: Demarrage du service
  lxc_container:
    name: '{{ item.name }}'
    container_command: |
      systemctl enable consul
      systemctl start consul
  with_items:
    - "{{ containers }}"

