---

- hosts: host 
  remote_user: root
  roles:
    - lxc_containers

- hosts: consul_cluster
  remote_user: root
  roles:
    - consul_install
    - consul_server

- hosts: leofs_manager
  remote_user: root
  roles:
    - leofs_install
    - leofs_manager

- hosts: leofs_storage
  remote_user: root
  roles:
    - leofs_install
    - leofs_storage

- hosts: leofs_gateway
  remote_user: root
  roles:
    - leofs_install
    - leofs_gateway

- hosts: leofs_manager
  remote_user: root
  roles:
    - leofs_start

- hosts: workflows
  remote_user: root
  roles:
    - consul_install
    - consul_agent

- hosts: operations
  remote_user: root
  roles:
    - consul_install
    - consul_agent
