---

- hosts: host 
  remote_user: root
  roles:
    - lxc_containers

- hosts: consul_cluster
  remote_user: root
  roles:
    - consul_install
    - consul_server

- hosts: ceph_cluster
  remote_user: root
  roles:
    - ceph_install

- hosts: ceph_admin
  remote_user: root
  roles:
    - ceph_install
    - ceph_deploy

- hosts: workflows
  remote_user: root
  roles:
    - consul_install
    - consul_agent
    - ditrit_common
    - ditrit_workflows
    - consul_reload

- hosts: operations
  remote_user: root
  roles:
    - consul_install
    - consul_agent
    - ditrit_common
    - ditrit_operations
    - consul_reload

- hosts: managers
  remote_user: root
  roles:
    - consul_install
    - consul_agent
    - ditrit_common
    - ditrit_managers



